import rawMap from "./domain-map.json";

/**
 * Domain -> Purdue source-institution entry. Generated by
 * scripts/build-domain-map.mjs (top-enrollment US schools + Indiana locals),
 * every code pinned against Purdue's own directory — never guessed.
 * Fallback for unmapped domains is the popup's global search.
 */

export interface SchoolEntry {
  code: string; // Purdue's 6-char code, e.g. "003825"
  name: string; // display name as Purdue lists it
  location: string; // "US"
  state: string; // "IN"
}

const DOMAIN_MAP: Record<string, SchoolEntry> = rawMap as Record<string, SchoolEntry>;

/** Match a hostname (or any subdomain of it) to a known school. */
export function domainToSchool(hostname: string): SchoolEntry | null {
  const h = hostname.toLowerCase().replace(/^www\./, "");
  const parts = h.split(".");
  for (let i = 0; i < parts.length - 1; i++) {
    const candidate = parts.slice(i).join(".");
    const hit = DOMAIN_MAP[candidate];
    if (hit) return hit;
  }
  return null;
}

/** Case/spacing-tolerant search over a school list (from p_ajax). */
export function searchSchools(
  list: { label: string; value: string }[],
  query: string,
): { label: string; value: string }[] {
  const q = query.toLowerCase().trim();
  if (!q) return list;
  return list.filter((s) => s.label.toLowerCase().includes(q));
}
